version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "⚡deps(workflow)"
      prefix-development: "⚡deps(workflow)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    assignees:
      - "yanosea"
    reviewers:
      - "yanosea"
