# config
[config]
skip_core_tasks = true
# nixos
## init
[tasks."nix.init"]
description = "yanoNixOs config init"
script = '''
./scripts/init/nixos.sh
'''
## install
[tasks."nix.install"]
description = "yanoNixOs install all packages"
script = '''
./scripts/install/nixos.sh
'''
## update
[tasks."nix.update"]
description = "yanoNixOs update all (config, packages)"
script = '''
./scripts/update/nixos.sh
'''
## apply system
[tasks."nix.apply.system"]
description = "yanoNixOs system config apply"
script = '''
sudo nixos-rebuild switch --flake .#yanoNixOs
'''
## apply home
[tasks."nix.apply.home"]
description = "yanoNixOs install packages"
script = '''
home-manager switch --flake .#yanosea@yanoNixOs
'''
# nixos wsl
## init
[tasks."wsl.init"]
description = "yanoNixOsWsl config init"
script = '''
./scripts/init/nixos_wsl.sh
'''
## install
[tasks."wsl.install"]
description = "yanoNixOsWsl install packages"
script = '''
./scripts/install/nixos_wsl.sh
'''
## update
[tasks."wsl.update"]
description = "yanoNixOsWsl update all (config, packages)"
script = '''
./scripts/update/nixos_wsl.sh
'''
## apply system
[tasks."wsl.apply.system"]
description = "yanoNixOsWsl system config apply"
script = '''
sudo nixos-rebuild switch --flake .#yanoNixOsWsl
'''
## apply home
[tasks."wsl.apply.home"]
description = "yanoNixOsWsl config apply"
script = '''
home-manager switch --flake .#yanosea@yanoNixOsWsl
'''
# darwin
## init
[tasks."darwin.init"]
description = "yanoMac config init"
script = '''
./scripts/init/darwin.sh
'''
## install
[tasks."darwin.install"]
description = "yanoMac install packages"
script = '''
./scripts/install/darwin.sh
'''
## update
[tasks."darwin.update"]
description = "yanoMac update all (config, packages)"
script = '''
./scripts/update/darwin.sh
'''
## apply system
[tasks."darwin.apply.system"]
description = "yanoMac system config apply"
script = '''
sudo rm -r ~/.nix-defexpr && sudo nix-channel --update
sudo darwin-rebuild switch --flake .#yanoMac
'''
## apply home
[tasks."darwin.apply.home"]
description = "yanoMac config apply"
script = '''
export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
home-manager switch --flake .#yanosea@yanoMac --extra-experimental-features "nix-command flakes" --impure
'''
# misc
## check
[tasks."misc.check"]
description = "check config"
script = '''
nix flake check --extra-experimental-features "nix-command flakes"
'''
## clean
[tasks."misc.clean"]
description = "clean up result directory"
clear = true
script = '''
rm -rf result
'''
## format
[tasks."misc.format"]
description = "run nix formatter"
script = '''
treefmt
'''
## gc
[tasks."misc.gc"]
description = "run nix gc"
script = '''
sudo nix profile wipe-history --extra-experimental-features "nix-command flakes" --profile /nix/var/nix/profiles/system --older-than 7d
sudo nix store gc --debug --extra-experimental-features "nix-command flakes"
'''
## update
[tasks."misc.update"]
description = "update flake.lock file"
script = '''
nix flake lock --update-input nixpkgs --extra-experimental-features "nix-command flakes"
'''
