[config]
skip_core_tasks = true

[env]
HOST = { script = ["hostname"] }

# nixos wsl
[tasks."yanoNixOSWsl:init"]
extend = "nixos_wsl:init"
env = { HOST = "yanoNixOSWsl" }

[tasks."nixos_wsl:init"]
description = "Run nixos-rebuild switch to initialize nixos wsl env"
script = '''
sudo nixos-rebuild switch --flake ".#${HOST}" --show-trace
sudo shutdown -h now
'''

[tasks."yanoNixOSWsl:init_after"]
description = "Run init script"
script = '''
./scripts/init/nixos_wsl.sh
'''

[tasks."yanoNixOSWsl:apply"]
extend = "nixos_wsl:apply"
env = { HOST = "yanoNixOSWsl" }

[tasks."nixos_wsl:apply"]
description = "Run nixos-rebuild switch to to apply changes to nixos wsl env"
script = '''
sudo nixos-rebuild switch --flake ".#${HOST}" --show-trace
'''

[tasks."yanoNixOSWsl:install"]
description = "Run install script script"
script = '''
./scripts/install/nixos_wsl.sh
'''

[tasks."yanoNixOSWsl:update"]
description = "Run update script script"
script = '''
./scripts/update/nixos_wsl.sh
'''

# nixos
[tasks."yanoNixOS:init"]
description = "Run init script"
script = '''
./scripts/init/nixos.sh
'''

[tasks."yanoNixOS:apply"]
description = "Run nixos-rebuild switch"
extend = "nixos:apply"
env = { HOST = "yanoNixOS" }

[tasks."nixos:apply"]
script = '''
sudo nixos-rebuild switch --flake ".#${HOST}" --show-trace
'''

[tasks."yanoNixOS:install"]
description = "Run install script script"
script = '''
./scripts/install/nixos.sh
'''

[tasks."yanoNixOS:update"]
description = "Run update script script"
script = '''
./scripts/update/nixos.sh
'''

# darwin
[tasks."yanoMac:init"]
description = "Run init script"
script = '''
sudo rm -r ~/.nix-defexpr && sudo nix-channel --update
nix build .#darwinConfigurations.${HOST}.system --extra-experimental-features 'nix-command flakes' --debug
sudo ./result/sw/bin/darwin-rebuild switch --flake ".#${HOST}"
./scripts/init/darwin.sh
'''

[tasks."yanoMac:apply"]
extend = "darwin:apply"
env = { HOST = "yanoMac" }

[tasks."darwin:apply"]
script = '''
sudo rm -r ~/.nix-defexpr && sudo nix-channel --update
nix build .#darwinConfigurations.${HOST}.system --extra-experimental-features 'nix-command flakes' --debug
sudo ./result/sw/bin/darwin-rebuild switch --flake ".#${HOST}"
'''

[tasks."yanoMac:install"]
description = "Run install script script"
script = '''
sudo rm -r ~/.nix-defexpr && sudo nix-channel --update
./scripts/install/darwin.sh
'''

[tasks."yanoMac:update"]
description = "Run update script script"
script = '''
sudo rm -r ~/.nix-defexpr && sudo nix-channel --update
./scripts/update/darwin.sh
'''

# misc
[tasks.format]
description = "Run formatter"
command = "nix"
args = ["fmt"]

[tasks.update]
command = "nix"
args = ["flake", "lock", "--update-input", "nixpkgs"]

[tasks.check]
command = "nix"
args = ["flake", "check", "--extra-experimental-features", "nix-command", "--extra-experimental-features", "flakes"]

[tasks.gc]
script = '''
sudo nix profile wipe-history --extra-experimental-features 'nix-command flakes' --profile /nix/var/nix/profiles/system --older-than 7d
sudo nix store gc --debug --extra-experimental-features 'nix-command flakes'
'''

[tasks.clean]
clear = true
script = '''
rm -rf result
'''
