[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.rust]
command = "rustfmt"
options = ["--edition", "2024"]
includes = ["*.rs"]

[formatter.sh]
command = "shfmt"
options = ["-i", "2", "-ci", "-bn", "-sr"]
includes = ["*.sh"]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
