format = """
[░▒▓](#83c092)\
$os\
[](bg:#a7c080 fg:#83c092)\
$directory\
[](fg:#a7c080 bg:#2b3339)\
$git_branch\
$git_status\
[](fg:#2b3339 bg:#2d353b)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2d353b bg:#2b3339)\
$time\
[ ](fg:#2b3339)\
\n$character"""

[os]
format = "[ $symbol ]($style)"
style = "bg:#83c092 fg:#090c0c"
disabled = false

[os.symbols]
Windows = ""
Arch = ""
Macos = ""
NixOS = ""

[directory]
style = "fg:#55544a bg:#a7c080"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#2b3339"
format = '[[ $symbol $branch ](fg:#a7c080 bg:#2b3339)]($style)'

[git_status]
style = "bg:#2b3339"
format = '[[($all_status$ahead_behind )](fg:#a7c080 bg:#2b3339)]($style)'

[nodejs]
symbol = ""
style = "bg:#2d353b"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#2d353b)]($style)'

[rust]
symbol = ""
style = "bg:#2d353b"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#2d353b)]($style)'

[golang]
symbol = ""
style = "bg:#2d353b"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#2d353b)]($style)'

[php]
symbol = ""
style = "bg:#2d353b"
format = '[[ $symbol ($version) ](fg:#a7c080 bg:#2d353b)]($style)'

[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:#2b3339"
format = '[[   $time ](fg:#d3c6aa bg:#2b3339)]($style)'
