#!/bin/bash
# generate-handover.sh - drop a placeholder HANDOVER.md before compaction.
# Grok counterpart of configs/claude/hooks/generate-handover.sh.

set -euo pipefail

input=$(cat)
cwd=$(echo "$input" | jq -r '.cwd // empty')
trigger=$(echo "$input" | jq -r '.trigger // "unknown"')
session_id=$(echo "$input" | jq -r '.sessionId // .session_id // "unknown"')

# grok sets GROK_WORKSPACE_ROOT for every hook
if [ -z "$cwd" ]; then
  cwd="${GROK_WORKSPACE_ROOT:-$PWD}"
fi

output_file="$cwd/HANDOVER.md"
timestamp=$(date '+%Y-%m-%d %H:%M')

# don't clobber a real handover (written by $handover or by hand) with the
# generic placeholder; only the placeholder itself is safe to overwrite
if [ -f "$output_file" ] && ! head -n 1 "$output_file" | grep -q '^# Auto-generated note$'; then
  exit 0
fi

if [ -f "$output_file" ]; then
  cp "$output_file" "$output_file.bak"
fi

cat >"$output_file" <<HANDOVER
# Auto-generated note

- Generated at: $timestamp
- Trigger: $trigger
- Session: $session_id
- This file was auto-generated by PreCompact hook
- Run the \`handover\` skill to generate a detailed handover note

## Notice

- This is a snapshot taken just before context compaction
- Review this file at the start of the next session
HANDOVER

exit 0
