#!/bin/bash
set -euo pipefail

input=$(cat)
cwd=$(echo "$input" | jq -r '.cwd // empty')
trigger=$(echo "$input" | jq -r '.trigger // "unknown"')
session_id=$(echo "$input" | jq -r '.session_id // "unknown"')

if [ -z "$cwd" ]; then
  cwd="${CLAUDE_PROJECT_DIR:-.}"
fi

output_file="$cwd/HANDOVER.md"
timestamp=$(date '+%Y-%m-%d %H:%M')

if [ -f "$output_file" ]; then
  cp "$output_file" "$output_file.bak"
fi

cat >"$output_file" <<EOF
# Auto-generated note

- Generated at: $timestamp
- Trigger: $trigger
- Session: $session_id
- This file was auto-generated by PreCompact hook
- Run /handover to generate a detailed handover note

## Notice

- This is a snapshot taken just before context compaction
- Review this file at the start of the next session
EOF

exit 0
