shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = '{% for file in files %}zsh-defer source "{{ file }}"{% endfor %}'
fpath_comp = 'fpath=("{{ dir }}/completions" $fpath)'

[plugins.compinit]
inline = "autoload -Uz compinit && compinit -d $XDG_STATE_HOME/zsh/.zcompdump"

[plugins.starship]
inline = "eval \"$(starship init zsh)\""

[plugins.fzf-init]
inline = 'zvm_after_init() { source <(fzf --zsh); }'

[plugins.zsh-vim-mode]
github = "jeffreytse/zsh-vi-mode"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-abbrev-alias]
github = "momo-lab/zsh-abbrev-alias"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["fpath_comp", "defer"]

[plugins.per-directory-history]
github = "jimhester/per-directory-history"
apply = ["defer"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]

[plugins.zoxide]
inline = "zsh-defer eval \"$(zoxide init zsh)\""

[plugins.pyenv]
inline = "zsh-defer eval \"$(pyenv init -)\""

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
