name: Auto Merge Dependency Update PR

on:
  pull_request_target:
    types: [opened, labeled, synchronize]
  workflow_run:
    workflows: ["Update Nix Flake Dependencies"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  find-pr:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success'
    outputs:
      pr_number: ${{ steps.find-pr.outputs.pr_number }}
      branch_name: ${{ steps.find-pr.outputs.branch_name }}
      found: ${{ steps.find-pr.outputs.found }}
    steps:
      - name: find associated PR
        id: find-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # alternative approach using direct PR search
          echo "Searching for dependency update PRs..."

          # get recent PRs and filter for our criteria
          PR_LIST=$(gh pr list --base main --limit 10 --json number,headRefName,labels --jq '.')
          echo "$PR_LIST" > /tmp/pr_list.json

          # extract matching PR with jq
          MATCHING_PR=$(jq -r '[.[] |
            select(.headRefName | startswith("auto-update/flake-lock/")) |
            select(.labels | map(.name) | any(. == "dependencies" or . == "automated")) |
            {number: .number, headRefName: .headRefName}] | first // {}' /tmp/pr_list.json)

          # check if we found a matching PR
          if [[ $(echo "$MATCHING_PR" | jq 'has("number")') == "true" ]]; then
            PR_NUMBER=$(echo "$MATCHING_PR" | jq -r '.number')
            HEAD_REF=$(echo "$MATCHING_PR" | jq -r '.headRefName')
            echo "PR #$PR_NUMBER ($HEAD_REF) is a valid dependency update PR"
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
            echo "branch_name=$HEAD_REF" >> $GITHUB_OUTPUT
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "No matching PR found"
            echo "found=false" >> $GITHUB_OUTPUT
          fi

  auto-approve-and-merge:
    runs-on: ubuntu-latest
    needs: find-pr
    if: needs.find-pr.outputs.found == 'true'
    env:
      PR_NUMBER: ${{ needs.find-pr.outputs.pr_number }}
      BRANCH_NAME: ${{ needs.find-pr.outputs.branch_name }}
      GITHUB_TOKEN: ${{ secrets.YANONIXFILES_AUTO_MERGE_PAT }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: auto approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.YANONIXFILES_AUTO_MERGE_PAT }}
          pull-request-number: ${{ needs.find-pr.outputs.pr_number }}

      - name: enable auto-merge and wait for completion
        run: |
          # verify PR exists
          if ! gh pr view "$PR_NUMBER" --json number &>/dev/null; then
            echo "PR #$PR_NUMBER not found or not accessible"
            exit 0
          fi

          # enable auto-merge
          if gh pr merge --auto --merge "$PR_NUMBER"; then
            echo "Auto-merge enabled for PR #$PR_NUMBER"
          else
            echo "Failed to enable auto-merge for PR #$PR_NUMBER"
            exit 0
          fi

          # wait for merge to complete
          MAX_WAIT_TIME=300  # 5 minutes
          POLLING_INTERVAL=10  # check every 10 seconds
          START_TIME=$(date +%s)

          while true; do
            CURRENT_TIME=$(date +%s)
            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))

            if [ $ELAPSED_TIME -gt $MAX_WAIT_TIME ]; then
              echo "Timeout waiting for PR to merge after ${MAX_WAIT_TIME}s"
              exit 0
            fi

            PR_STATE=$(gh pr view "$PR_NUMBER" --json state --jq .state 2>/dev/null || echo "UNKNOWN")
            if [ "$PR_STATE" == "MERGED" ]; then
              echo "PR #$PR_NUMBER has been merged successfully"
              break
            elif [ "$PR_STATE" == "UNKNOWN" ]; then
              echo "Could not determine PR state, it might have been deleted"
              break
            fi

            echo "Waiting for PR to merge (${ELAPSED_TIME}s elapsed)... Current state: $PR_STATE"
            sleep $POLLING_INTERVAL
          done

      - name: delete source branch if it exists
        run: |
          # check if branch exists and delete it if present
          if gh api repos/$GITHUB_REPOSITORY/branches/$BRANCH_NAME --silent 2>/dev/null; then
            echo "Branch $BRANCH_NAME still exists, deleting it"
            gh api -X DELETE repos/$GITHUB_REPOSITORY/git/refs/heads/$BRANCH_NAME && \
              echo "Branch $BRANCH_NAME deleted successfully" || \
              echo "Failed to delete branch $BRANCH_NAME"
          else
            echo "Branch $BRANCH_NAME already deleted or does not exist"
          fi
