name: Auto merge updating flake.lock PR

on:
  pull_request_target:
    types:
      - opened
      - labeled
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'automated') &&
      startsWith(github.event.pull_request.head.ref, 'auto-update/flake-lock/')
    permissions:
      pull-requests: write
    steps:
      - name: auto approve PR
        uses: hmarr/auto-approve-action@v4

  auto-merge:
    runs-on: ubuntu-latest
    needs: auto-approve
    if: |
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'automated') &&
      startsWith(github.event.pull_request.head.ref, 'auto-update/flake-lock/')
    steps:
      - name: enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
