name: Auto merge updating flake.lock PR

on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize
  pull_request_target:
    types:
      - opened
      - labeled
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'automated') &&
      startsWith(github.event.pull_request.head.ref, 'auto-update/flake-lock/')
    permissions:
      pull-requests: write
    steps:
      - name: auto approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    runs-on: ubuntu-latest
    needs: auto-approve
    if: |
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'automated') &&
      startsWith(github.event.pull_request.head.ref, 'auto-update/flake-lock/')
    steps:
      - name: enable auto-merge
        run: |
          echo "PR URL: $PR_URL"
          echo "PR Labels: ${{ toJSON(github.event.pull_request.labels) }}"
          echo "PR Branch: ${{ github.event.pull_request.head.ref }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          gh pr merge --auto --merge "$PR_NUMBER"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
